package com.example.electroec.entity;

import java.io.Serializable;
import java.util.Date;

/**
 * customers モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Customers implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** id. */
	private Integer id;

	/** first_name. */
	private String firstName;

	/** last_name. */
	private String lastName;

	/** address01. */
	private String address01;

	/** address02. */
	private String address02;

	/** address03. */
	private String address03;

	/** tel. */
	private Integer tel;

	/** email. */
	private String email;

	/** zip. */
	private Integer zip;

	/** img01. */
	private String img01;

	/** img02. */
	private String img02;

	/** img03. */
	private String img03;

	/** status. */
	private Integer status;

	/** insert_date. */
	private Date insertDate;

	/** update_date. */
	private Date updateDate;

	/** insert_user. */
	private String insertUser;

	/** update_user. */
	private String updateUser;

	/**
	 * コンストラクタ.
	 */
	public Customers() {
	}

	/**
	 * id を設定します.
	 * 
	 * @param id
	 *            id
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * id を取得します.
	 * 
	 * @return id
	 */
	public Integer getId() {
		return this.id;
	}

	/**
	 * first_name を設定します.
	 * 
	 * @param firstName
	 *            first_name
	 */
	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	/**
	 * first_name を取得します.
	 * 
	 * @return first_name
	 */
	public String getFirstName() {
		return this.firstName;
	}

	/**
	 * last_name を設定します.
	 * 
	 * @param lastName
	 *            last_name
	 */
	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	/**
	 * last_name を取得します.
	 * 
	 * @return last_name
	 */
	public String getLastName() {
		return this.lastName;
	}

	/**
	 * address01 を設定します.
	 * 
	 * @param address01
	 *            address01
	 */
	public void setAddress01(String address01) {
		this.address01 = address01;
	}

	/**
	 * address01 を取得します.
	 * 
	 * @return address01
	 */
	public String getAddress01() {
		return this.address01;
	}

	/**
	 * address02 を設定します.
	 * 
	 * @param address02
	 *            address02
	 */
	public void setAddress02(String address02) {
		this.address02 = address02;
	}

	/**
	 * address02 を取得します.
	 * 
	 * @return address02
	 */
	public String getAddress02() {
		return this.address02;
	}

	/**
	 * address03 を設定します.
	 * 
	 * @param address03
	 *            address03
	 */
	public void setAddress03(String address03) {
		this.address03 = address03;
	}

	/**
	 * address03 を取得します.
	 * 
	 * @return address03
	 */
	public String getAddress03() {
		return this.address03;
	}

	/**
	 * tel を設定します.
	 * 
	 * @param tel
	 *            tel
	 */
	public void setTel(Integer tel) {
		this.tel = tel;
	}

	/**
	 * tel を取得します.
	 * 
	 * @return tel
	 */
	public Integer getTel() {
		return this.tel;
	}

	/**
	 * email を設定します.
	 * 
	 * @param email
	 *            email
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * email を取得します.
	 * 
	 * @return email
	 */
	public String getEmail() {
		return this.email;
	}

	/**
	 * zip を設定します.
	 * 
	 * @param zip
	 *            zip
	 */
	public void setZip(Integer zip) {
		this.zip = zip;
	}

	/**
	 * zip を取得します.
	 * 
	 * @return zip
	 */
	public Integer getZip() {
		return this.zip;
	}

	/**
	 * img01 を設定します.
	 * 
	 * @param img01
	 *            img01
	 */
	public void setImg01(String img01) {
		this.img01 = img01;
	}

	/**
	 * img01 を取得します.
	 * 
	 * @return img01
	 */
	public String getImg01() {
		return this.img01;
	}

	/**
	 * img02 を設定します.
	 * 
	 * @param img02
	 *            img02
	 */
	public void setImg02(String img02) {
		this.img02 = img02;
	}

	/**
	 * img02 を取得します.
	 * 
	 * @return img02
	 */
	public String getImg02() {
		return this.img02;
	}

	/**
	 * img03 を設定します.
	 * 
	 * @param img03
	 *            img03
	 */
	public void setImg03(String img03) {
		this.img03 = img03;
	}

	/**
	 * img03 を取得します.
	 * 
	 * @return img03
	 */
	public String getImg03() {
		return this.img03;
	}

	/**
	 * status を設定します.
	 * 
	 * @param status
	 *            status
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * status を取得します.
	 * 
	 * @return status
	 */
	public Integer getStatus() {
		return this.status;
	}

	/**
	 * insert_date を設定します.
	 * 
	 * @param insertDate
	 *            insert_date
	 */
	public void setInsertDate(Date insertDate) {
		this.insertDate = insertDate;
	}

	/**
	 * insert_date を取得します.
	 * 
	 * @return insert_date
	 */
	public Date getInsertDate() {
		return this.insertDate;
	}

	/**
	 * update_date を設定します.
	 * 
	 * @param updateDate
	 *            update_date
	 */
	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	/**
	 * update_date を取得します.
	 * 
	 * @return update_date
	 */
	public Date getUpdateDate() {
		return this.updateDate;
	}

	/**
	 * insert_user を設定します.
	 * 
	 * @param insertUser
	 *            insert_user
	 */
	public void setInsertUser(String insertUser) {
		this.insertUser = insertUser;
	}

	/**
	 * insert_user を取得します.
	 * 
	 * @return insert_user
	 */
	public String getInsertUser() {
		return this.insertUser;
	}

	/**
	 * update_user を設定します.
	 * 
	 * @param updateUser
	 *            update_user
	 */
	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	/**
	 * update_user を取得します.
	 * 
	 * @return update_user
	 */
	public String getUpdateUser() {
		return this.updateUser;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Customers other = (Customers) obj;
		if (id == null) {
			if (other.id != null) {
				return false;
			}
		} else if (!id.equals(other.id)) {
			return false;
		}
		return true;
	}

}
