package com.example.electroec.entity;

import java.io.Serializable;
import java.util.Date;

/**
 * products モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Products implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** serial_num. */
	private String serialNum;

	/** name. */
	private String name;

	/** category_id. */
	private Integer categoryId;

	/** description. */
	private String description;

	/** price. */
	private Double price;

	/** brand_id. */
	private Integer brandId;

	/** status. */
	private Integer status;

	/** rating. */
	private Integer rating;

	/** insert_date. */
	private Date insertDate;

	/** update_date. */
	private Date updateDate;

	/** insert_user. */
	private String insertUser;

	/** update_user. */
	private String updateUser;

	/**
	 * コンストラクタ.
	 */
	public Products() {
	}

	/**
	 * serial_num を設定します.
	 * 
	 * @param serialNum
	 *            serial_num
	 */
	public void setSerialNum(String serialNum) {
		this.serialNum = serialNum;
	}

	/**
	 * serial_num を取得します.
	 * 
	 * @return serial_num
	 */
	public String getSerialNum() {
		return this.serialNum;
	}

	/**
	 * name を設定します.
	 * 
	 * @param name
	 *            name
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * name を取得します.
	 * 
	 * @return name
	 */
	public String getName() {
		return this.name;
	}

	/**
	 * category_id を設定します.
	 * 
	 * @param categoryId
	 *            category_id
	 */
	public void setCategoryId(Integer categoryId) {
		this.categoryId = categoryId;
	}

	/**
	 * category_id を取得します.
	 * 
	 * @return category_id
	 */
	public Integer getCategoryId() {
		return this.categoryId;
	}

	/**
	 * description を設定します.
	 * 
	 * @param description
	 *            description
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * description を取得します.
	 * 
	 * @return description
	 */
	public String getDescription() {
		return this.description;
	}

	/**
	 * price を設定します.
	 * 
	 * @param price
	 *            price
	 */
	public void setPrice(Double price) {
		this.price = price;
	}

	/**
	 * price を取得します.
	 * 
	 * @return price
	 */
	public Double getPrice() {
		return this.price;
	}

	/**
	 * brand_id を設定します.
	 * 
	 * @param brandId
	 *            brand_id
	 */
	public void setBrandId(Integer brandId) {
		this.brandId = brandId;
	}

	/**
	 * brand_id を取得します.
	 * 
	 * @return brand_id
	 */
	public Integer getBrandId() {
		return this.brandId;
	}

	/**
	 * status を設定します.
	 * 
	 * @param status
	 *            status
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * status を取得します.
	 * 
	 * @return status
	 */
	public Integer getStatus() {
		return this.status;
	}

	/**
	 * rating を設定します.
	 * 
	 * @param rating
	 *            rating
	 */
	public void setRating(Integer rating) {
		this.rating = rating;
	}

	/**
	 * rating を取得します.
	 * 
	 * @return rating
	 */
	public Integer getRating() {
		return this.rating;
	}

	/**
	 * insert_date を設定します.
	 * 
	 * @param insertDate
	 *            insert_date
	 */
	public void setInsertDate(Date insertDate) {
		this.insertDate = insertDate;
	}

	/**
	 * insert_date を取得します.
	 * 
	 * @return insert_date
	 */
	public Date getInsertDate() {
		return this.insertDate;
	}

	/**
	 * update_date を設定します.
	 * 
	 * @param updateDate
	 *            update_date
	 */
	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	/**
	 * update_date を取得します.
	 * 
	 * @return update_date
	 */
	public Date getUpdateDate() {
		return this.updateDate;
	}

	/**
	 * insert_user を設定します.
	 * 
	 * @param insertUser
	 *            insert_user
	 */
	public void setInsertUser(String insertUser) {
		this.insertUser = insertUser;
	}

	/**
	 * insert_user を取得します.
	 * 
	 * @return insert_user
	 */
	public String getInsertUser() {
		return this.insertUser;
	}

	/**
	 * update_user を設定します.
	 * 
	 * @param updateUser
	 *            update_user
	 */
	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	/**
	 * update_user を取得します.
	 * 
	 * @return update_user
	 */
	public String getUpdateUser() {
		return this.updateUser;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((serialNum == null) ? 0 : serialNum.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Products other = (Products) obj;
		if (serialNum == null) {
			if (other.serialNum != null) {
				return false;
			}
		} else if (!serialNum.equals(other.serialNum)) {
			return false;
		}
		return true;
	}

}
